version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make unittest

  push-docker-pr:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-image
      - run: ./scripts/push-docker-pr.sh
      - run:
          name: Re-run Docker Push if fail
          command: |
            sleep 20
            ./scripts/push-docker-pr.sh
          when: on_fail

  push-docker:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-image
      - run: ./scripts/push-docker.sh
      - run:
          name: Re-run Docker Push if fail
          command: |
            sleep 20
            ./scripts/push-docker.sh
          when: on_fail

workflows:
  version: 2
  pr-build:
    jobs:
      - lint
      - test
      - push-docker-pr:
          context: matterbuild-docker
          requires:
            - lint
            - test
  master-build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - push-docker:
          context: matterbuild-docker
          requires:
            - test
          filters:
            branches:
              only:
                - main
  tag-builds:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - push-docker:
          context: matterbuild-docker
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/