name: 'Docker build and push'
description: 'Builds and push Mattermost built images to dockerhub'
inputs:
  dockerhub-username: # id of input
    description: 'Dockerhub username'
    required: true
  dockerhub-password:
    description: 'Dockerhub password'
    required: true
  latest-tag:
    description: 'The tag to use as "latest"'
    default: 'latest'
  image-name:
    description: 'The name of the image to build'
    required: true
  is-release:
    description: 'If the push is a release'
    default: 'no'
runs:
  using: "composite"
  steps:
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.dockerhub-username }}
      password: ${{ inputs.dockerhub-password }}

  # For pull requests use a custom tag: `pr-{pr number}`
  - name: cd/push-docker-pr-tag
    uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
    if: ${{ github.event_name == 'pull_request' }}
    with:
      push: true
      tags: ${{ inputs.image-name }}:pr-${{ github.event.number }}

  # If pushing to the main branch, push the 'latest' tag and the version tag
  - name: cd/push-docker-version-tag
    uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
    if: ${{ inputs.is-release == 'yes' && github.event_name == 'push' && startsWith('v', github.ref_name) }}
    with:
      push: true
      tags: ${{ inputs.image-name }}:${{ github.ref_name }}

  - name: cd/push-docker-latest-tag
    uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
    if: ${{ inputs.is-release == 'yes' && github.event_name == 'push' }}
    with:
      push: true
      tags: ${{ inputs.image-name }}:${{ inputs.latest-tag }}
