name: cd

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

env:
  IMAGE_NAME: mattermost/backup-restore-tool
  LATEST_TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: cd/checkout-repo
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      with:
        fetch-depth: 1

    - name: Build and push
      uses: ./.github/actions/docker-push
      with:
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
        image-name: ${{ env.IMAGE_NAME }}
        latest-tag: ${{ env.LATEST_TAG }}
        main-branch: main
