name: ci

on:
  pull_request:
  push:
    branches:
    - master

permissions:
  contents: read

env:
  IMAGE_NAME: mattermost/backup-restore-tool

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: go.mod
        cache: true

    - name: ci/check-style
      run: make check-style

  test:
    runs-on: ubuntu-22.04
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        cache: true
        go-version-file: go.mod

    - name: ci/test
      run: make unittest

  scan:
    runs-on: ubuntu-22.04
    needs: [test, lint]
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: ci/build-docker
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
      with:
        load: true
        tags: "${{ env.IMAGE_NAME }}:test"

    - name: ci/scan-docker-security
      uses: anchore/scan-action@7037fa011853d5a11690026fb85feee79f4c946c # v7.3.2
      with:
        image: "${{ env.IMAGE_NAME }}:test"
        output-format: table
        only-fixed: true
        fail-build: false
        severity-cutoff: critical

  push:
    needs: [test, lint, scan]
    runs-on: ubuntu-22.04
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Build and push
      uses: ./.github/actions/docker-push
      with:
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
        image-name: ${{ env.IMAGE_NAME }}
